- name: Proxmox
  hosts: proxmox
  gather_facts: true
  become: true
  tasks:
    - name: Template login manager configuration
      ansible.builtin.template:
        src: logind.conf.j2
        dest: /etc/systemd/logind.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart login manager

    - name: Configure repositories
      block:
        - name: Remove Proxmox enterprise repository
          ansible.builtin.apt_repository:
            repo: deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise
            filename: pve-enterprise
            state: absent
            update_cache: true

        - name: Add Proxmox no-subscription repository
          ansible.builtin.apt_repository:
            repo: deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription
            filename: pve-no-subscription
            state: present
            update_cache: true

    - name: Install nginx
      ansible.builtin.apt:
        name:
          - nginx
        policy_rc_d: 101 # Prevent autostart

    - name: Configure nginx
      notify:
        - Stop nginx
      block:
        - name: Remove nginx default configuration
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - /etc/nginx/conf.d/default
            - /etc/nginx/sites-enabled/default
            - /etc/nginx/sites-available/default
            - /var/www/html/index.nginx-debian.html

        - name: Template nginx configuration
          ansible.builtin.template:
            src: proxmox.conf.j2
            dest: /etc/nginx/conf.d/proxmox.conf
            owner: root
            group: root
            mode: 0644

        - name: Ensure nginx override folder exists
          ansible.builtin.file:
            path: /etc/systemd/system/nginx.service.d
            state: directory
            mode: 0755

        - name: Template nginx override configuration
          ansible.builtin.template:
            src: override.conf.j2
            dest: /etc/systemd/system/nginx.service.d/override.conf
            owner: root
            group: root
            mode: 0644

    - name: Stop nginx if configuration has changed
      ansible.builtin.meta: flush_handlers

    - name: Ensure nginx is started
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Stop nginx
      ansible.builtin.service:
        name: nginx
        state: stopped

    - name: Restart login manager
      ansible.builtin.service:
        name: systemd-logind
        state: restarted
